In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("hw1 - Copy.csv")

In [8]:
df1 = df

In [9]:
df['Query'] = ['Query ' + str(i+1) for i in range(len(df))]

In [10]:
df

         Query  Overlap Count  Percent Overlap  Spearman Coefficient
0      Query 1           1.00             10.0                 1.000
1      Query 2           1.00             10.0                 1.000
2      Query 3           2.00             20.0                -1.000
3      Query 4           1.00             10.0                 0.000
4      Query 5           0.00              0.0                 0.000
..         ...            ...              ...                   ...
96    Query 97           0.00              0.0                 0.000
97    Query 98           2.00             20.0                 1.000
98    Query 99           0.00              0.0                 0.000
99   Query 100           0.00              0.0                 0.000
100  Query 101           1.27             12.7                 0.152

[101 rows x 4 columns]

In [18]:
df.iloc[100,0] = 'Averages'

In [19]:
df

         Query  Overlap Count  Percent Overlap  Spearman Coefficient
0      Query 1           1.00             10.0                 1.000
1      Query 2           1.00             10.0                 1.000
2      Query 3           2.00             20.0                -1.000
3      Query 4           1.00             10.0                 0.000
4      Query 5           0.00              0.0                 0.000
..         ...            ...              ...                   ...
96    Query 97           0.00              0.0                 0.000
97    Query 98           2.00             20.0                 1.000
98    Query 99           0.00              0.0                 0.000
99   Query 100           0.00              0.0                 0.000
100   Averages           1.27             12.7                 0.152

[101 rows x 4 columns]

In [20]:
df.to_csv('hw1.csv', index=False)